spring.application.name=SpringProjectNew


#logging.level.root=INFO


server.error.include-stacktrace=never
spring.datasource.url=jdbc:postgresql://localhost:5432/TestDataBase
spring.datasource.username=postgres
spring.datasource.password=Deepak@2024!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


